### ISSUE TITLE
10K is pretty small, why not 1M ?

### ISSUE THREAD

**Issue by mgolub2** [uncheckederror/CSharpBenchmarks#1]
10,000 is pretty small for an array, it would be interesting to see if the differences were closer when using much larger data structures.

**Comment by uncheckederror** [comment]
I picked 10K for no particular reason. This is a good point though, we should probably do something like 1 to 1M by orders of magnitude.

**Comment by uncheckederror** [comment]
This issue is resolved in commit 45995f7. Data structure sizes now range from 10 to 1M.
